### ISSUE TITLE
Add new line at the end of the log

### ISSUE THREAD

**Issue by cmwd** [pinojs/pino-syslog#1]
Currently, transform doesn't add a newline to the end of the log. If it's something required by syslog spec can we add this feature by the flag?

If you agree I can prepare a PR with this feature.

Cheers,
Piotr

**Comment by jsumners** [comment]
I don't see where either RFC3164 or RFC5424 specify that logs should be terminated with a new line. But I also don't see them prohibiting it.

If you would like to provide a PR for this, please include an example of where it would be necessary, e.g. "`-n` terminate with a newline for receivers like FooReceiver".
