### ISSUE TITLE
Config file attributes are overriden by default config

### ISSUE THREAD

**Issue by eleon-sqli** [pinojs/pino-syslog#10]
The options described in an external configuration file (--config flag) are overriden by the default internal config values.
The final option object should be constructed just before the transport assignment block:

````
const options = Object.assign({}, defaults, jsonOptions, args);
````

I would like to create a PR but I can't push a branch on this repo.

**Comment by jsumners** [comment]
See https://guides.github.com/activities/forking/

Also see https://github.com/pinojs/pino-syslog/pull/8#pullrequestreview-540972972 and https://github.com/pinojs/pino-syslog/pull/8#pullrequestreview-541250436

**Comment by eleon-sqli** [comment]
Thanks... oups forgot to fork...
