### ISSUE TITLE
Support for npm/yarn scripts

### ISSUE THREAD

**Issue by cmwd** [pinojs/pino-syslog#2]
This transform works only if an app is executed directly from the node. Because npm/yarn adds own non-json logs to the output it throws `SyntaxError: Unexpected end of JSON input`.

Maybe we could simply detect if the log comes from pino and if not just ignore it?

Thanks,
Piotr

**Comment by jsumners** [comment]
Yes. It should also validate the JSON parsing like https://github.com/pinojs/pino-filter/blob/5445b1621391551a05b53a89379b49ed80de4e1c/index.js#L116-L120
