### ISSUE TITLE
Compatibility with Pino v8 as Pino Transport

### ISSUE THREAD

**Issue by piotr-cz** [pinojs/pino-syslog#22]
Is the transport available with Pino v8?

I'm trying to use it wit Fastify as described in [docs](https://fastify.dev/docs/latest/Reference/Logging/)

```ts
const fastify = Fastify({
  disableRequestLogging: true,
  logger: {
    enabled: true,
    level: 'info',
    transport: {
      target: 'pino-syslog',
    },
  },
})
```
but unlike `pino-pretty`, there is no output.

According to [pino docs](https://getpino.io/#/docs/transports?id=pino-syslog) this is a *Legacy transport* and should work at least with pipelines - but not for me.

**Comment by jsumners** [comment]
Have you reviewed https://github.com/pinojs/pino-syslog#usage-as-pino-transport?
